services:
  - type: web
    name: qr-menu-frontend
    env: static
    buildCommand: npm install && npm run build:render
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: CI
        value: false
      - key: REACT_APP_API_URL
        value: https://qwiks-backend.onrender.com/api
      - key: REACT_APP_BACKEND_URL
        value: https://qwiks-backend.onrender.com
    buildFilter:
      paths:
        - frontend/**
