services:
  - type: web
    name: qr-menu-frontend
    env: static
    buildCommand: CI=false npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
